config/routes.rb
Test1::Application.routes.draw do
  resources :widgets
  resources :calculators do
    collection do
      get :stuff
    end
    member do
      get :other_stuff
    end
  end

  resources :results

  root to: "calculators#index"

  

end

app/models/calculator.rb
class Calculator < ActiveRecord::Base
  after_initialize :setup_defaults
  has_many :results

  def clear
    self.accumulator = 0.0 
    self.current_entry = ""
    self.current_operation = ""
  end


  def handle_key(key)
    puts "in handle_key"
    case key
    when /^clear$/
      self.results << Result.new(result_type: 'operation', operation: '--clear--')
      self.results << Result.new(result_type: 'value', value: 0.0)
      self.clear
    when /^\d$/
      puts "in number"
      self.current_entry += key
    when /^equal$/
      puts "in equal"
      value = self.current_entry.to_f
      self.results << Result.new(result_type: 'value', value: value)
      apply_operation(self.current_operation, value)
      self.results << Result.new(result_type: 'operation', operation: '=')
      self.results << Result.new(result_type: 'value', value: self.accumulator)
      self.current_entry = ""
      self.current_operation = ""
    when /^(plus|minus|times|divide)$/
      puts "in operation"
      value = self.current_entry.to_f
      accumulator_changed = false
      puts "value = #{value}"
      if self.current_operation.present?
        puts "no current_operation present"
        apply_operation(self.current_operation, value)
        puts "new accumulator = #{self.accumulator}"
        accumulator_changed = true
      else
        puts "current operation present"
        if self.current_entry.present?
          self.results << Result.new(result_type: 'operation', operation: '---')
          self.accumulator = value
          accumulator_changed = true
        end
      end
      if accumulator_changed
        self.results << Result.new(result_type: 'value', value: self.accumulator)
      end
      self.current_operation = key
      self.results << Result.new(result_type: 'operation', operation: key)
      self.current_entry = ""
    else
      puts "in else case"
    end
  end

  OP_NAME_TO_SYMBOL = {
    'plus'   => '+',
    'minus'  => '-',
    'times'  => '*',
    'divide' => '/'
  }

  def self.operation_name_to_symbol(operation_name)
    OP_NAME_TO_SYMBOL[operation_name]
  end
=begin
  def to_json
    json = super
    json["results"] = self.results.by_most_recent.limit(20)
    json
  end
=end

  private

  def apply_operation(operation, value)
    case operation
    when /plus/
      self.accumulator += value
    when /minus/
      self.accumulator -= value
    when /times/
      self.accumulator *= value
    when /divide/
      self.accumulator /= value
    end
  end

  def setup_defaults
    self.accumulator ||= 0.0 
    self.current_entry ||= ""
    self.current_operation ||= ""
  end
end

app/models/memory_location.rb
class MemoryLocation < ActiveRecord::Base
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :calculator

  scope :by_most_recent, -> { order("created_at DESC") }
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calculators_controller.rb
class CalculatorsController < ApplicationController
  # FIXME: implement filters
  #before_filter :load_calculator, only: [:show, :update]

  def show
    load_calculator
  end

  def index
    calculator = Calculator.create(guid: SecureRandom.hex)
    redirect_to calculator_path(id: calculator.guid)
  end

  def update
    load_calculator
    @calculator.update(calculator_params)
    @calculator.handle_key(params[:key]) if params[:key] 
    @calculator.save

    respond_to do |format|
      format.html { redirect_to calculator_path(id: @calculator.guid) }
      format.json { head :ok }
    end
  end

  private

  if RUBY_ENGINE != "opal"
  include CalculatorsControllerServer
  end

  def load_calculator
    id = params[:id]
    if /^\d+$/.match(id)
      @calculator = Calculator.find(params[:id])
    else
      @calculator = Calculator.where(guid: params[:id]).first
    end
  end
end

app/controllers/calculators_controller_server.rb
module CalculatorsControllerServer
  def calculator_params
    params.require(:calculator).permit(:current_entry, :accumulator, :current_operation)
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @calculator = load_calculator(params[:calculator_id])
    @results = @calculator.results.reverse
  end

  def create
    result = Result.create(result_params)
    respond_to do |format|
      format.json { render json: result }
    end
  end

  private

  if RUBY_ENGINE != "opal"
  include ResultsControllerServer
  end

  def load_calculator(id)
    if /^\d+$/.match(id)
      @calculator = Calculator.find(id)
    else
      @calculator = Calculator.where(guid: id).first
    end
  end
end

app/controllers/results_controller_server.rb
module ResultsControllerServer
  def result_params
    params.require(:result).permit(:operation, :result_type, :value, :calculator_id)
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render action: 'show', status: :created, location: @widget }
      else
        format.html { render action: 'new' }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/calculators/_accumulator.html.erb
<%= @calculator.accumulator %> <%= @calculator.current_operation.present? ? "| #{Calculator::operation_name_to_symbol(@calculator.current_operation)}" : "" %>

app/views/calculators/show.html.erb
<div class="main">
  <div id="calculator">
    <%= form_for @calculator do |f| %>
      <div class="accumulator" id="accumulator">
        <%# render partial: 'accumulator', locals: {calculator: @calculator} %>
      </div>
      <div>
        <%= f.text_field :current_entry, class: 'keypad-input', id: 'current_entry' %>
      </div>
      <div>
        <%= button_tag 'clear', class: 'two_wide_keypad', name: 'key', value: 'clear' %>
        <span class="two_wide_link_button"><%= link_to('tape', results_path(calculator_id: @calculator.guid), class: "link_button", id: 'tape') %></span>
      </div>
      <div>
        <%= button_tag '1', id: 'keypad-1',      class: 'keypad', name: 'key', value: '1' %>
        <%= button_tag '2', id: 'keypad-2',      class: 'keypad', name: 'key', value: '2' %>
        <%= button_tag '3', id: 'keypad-3',      class: 'keypad', name: 'key', value: '3' %>
        <%= button_tag '+', id: 'keypad-plus',   class: 'keypad', name: 'key', value: 'plus' %>
      </div>
      <div>
        <%= button_tag '4', id: 'keypad-4',      class: 'keypad', name: 'key', value: '4' %>
        <%= button_tag '5', id: 'keypad-5',      class: 'keypad', name: 'key', value: '5' %>
        <%= button_tag '6', id: 'keypad-6',      class: 'keypad', name: 'key', value: '6' %>
        <%= button_tag '-', id: 'keypad-minus',  class: 'keypad', name: 'key', value: 'minus'  %>
      </div>
      <div>
        <%= button_tag '7', id: 'keypad-7',      class: 'keypad', name: 'key', value: '7'  %>
        <%= button_tag '8', id: 'keypad-8',      class: 'keypad', name: 'key', value: '8'  %>
        <%= button_tag '9', id: 'keypad-9',      class: 'keypad', name: 'key', value: '9'  %>
        <%= button_tag '*', id: 'keypad-times',  class: 'keypad', name: 'key', value: 'times'  %>
      </div>
      <div>
        <%= button_tag "=", id: 'keypad-equal',  class: "keypad", name: "key", value: "equal" %>
        <%= button_tag "0", id: 'keypad-0',      class: "keypad", name: "key", value: "0"  %>
        <%= button_tag ".", id: 'keypad-dot',    class: "keypad", name: "key", value: "dot"  %>
        <%= button_tag "/", id: 'keypad-divide', class: "keypad", name: "key", value: "divide"  %>
      </div>
    <% end %>
  </div>
  <div id="results"></div>
</div>

<% content_for :script do %>
  $(function() {
    Opal.CalculatorApplication.$instance().$launch('<%= @calculator.to_json(root: true, include: :results).html_safe %>')
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test1</title>
  <meta name="viewport" content="width=device-width">
  <%# stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%# javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="application/javascript">
    <%= yield :script %>
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/index.html.erb
<div class="main">
  <div id="results">
    <h1>Results</h1>
    <%= link_to("Back", calculator_path(@calculator.guid), id: 'back') %>
    <% @results.each do |result| %>
      <div>
        <% if result.result_type == 'value' %>
          <%= result.value %>
        <% else %>
          <%= result.operation %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div id="calculator">
  </div>
</div>


<% content_for :script do %>
  $(function() {
    Opal.CalculatorApplication.$instance().$launch('<%= (@results + [@calculator]).to_json(root: true).html_safe %>')
  });
<% end %>

app/views/widgets/_form.html.erb
<%= form_for(widget) do |f| %>
  <% if widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions" #{control.save_id}>
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/_show.html.erb
<p>
  <strong>Name:</strong>
  <span class="<%= control.widget_show_class %>"><%= widget.name %></span>
</p>

<p>
  <strong>Color:</strong>
  <span class="<%= control.widget_show_class %>"><%= widget.color %></span>
</p>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%# InlineWidget.new(self, @widget, true).render %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>


<script type="text/javascript">
  //var widget_ruby = '<%= @widget.as_json.inspect.html_safe %>'
  //Opal.WidgetController.$load_and_start(widget_ruby, "edit");
</script>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<div id="stuff"></div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.color %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<%= InlineWidget.new(self, @widget, false).render %>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>

<script type="text/javascript">
  var widget = Opal.parse("<%= @widget.as_json.inspect.html_safe %>")
  Opal.WidgetController.$load_and_start(widget, "edit");
</script>